name: Update URLs List

on:
  schedule:
    - cron: "20 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run update script
        run: |
          chmod +x update_urls.sh
          ./update_urls.sh

      - name: Commit changes if needed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add -A
            git commit -m "Update urls.lst"
            git push
          else
            echo "No changes"
          fi
